spring:
  application:
    name: shares
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ## JPA ??
  # create : SessionFactory? ??? ? ???? ??? ?? ??. (sql?? ??? ???? ???? ?? ???? ??????.)
  # create-drop : create? ?????, SessionFactory? ???? ?? ???? drop???.
  # update : SessionFactory? ??? ? Object? ???? ???? alter ???. ???? ???.
  # validate : update?? Object? ?????, ???? ???? ???? ??, Object? ???? ??? ???? ??? ?????.
  # none : ???? ??
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
jasypt: # ???? ??? ??
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_KEY}
